/**
 * Supabase Database Types
 * 
 * This file will be auto-generated by Supabase CLI once you set up your project:
 * npx supabase gen types typescript --project-id <your-project-id> > src/lib/database.types.ts
 * 
 * For now, this is a placeholder with the expected schema.
 */

export interface Database {
	public: {
		Tables: {
			favorites: {
				Row: {
					id: string;
					user_id: string;
					item_type: 'material' | 'hardware' | 'finish';
					item_id: number;
					item_sku: string | null;
					notes: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					item_type: 'material' | 'hardware' | 'finish';
					item_id: number;
					item_sku?: string | null;
					notes?: string | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					item_type?: 'material' | 'hardware' | 'finish';
					item_id?: number;
					item_sku?: string | null;
					notes?: string | null;
					created_at?: string;
				};
			};
			profiles: {
				Row: {
					id: string;
					email: string;
					full_name: string | null;
					avatar_url: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					email: string;
					full_name?: string | null;
					avatar_url?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					email?: string;
					full_name?: string | null;
					avatar_url?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
		};
		Views: Record<string, never>;
		Functions: Record<string, never>;
		Enums: Record<string, never>;
	};
}

// Convenience types
export type Favorite = Database['public']['Tables']['favorites']['Row'];
export type Profile = Database['public']['Tables']['profiles']['Row'];
